version: '3.3'

services:
  sqlserver:
    build: .
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8083:8080"
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver

volumes:
  sqlserver_data:
