version: '3.3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "root"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P root -i /docker-entrypoint-initdb.d/init-db.sql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8083:8080"
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver

volumes:
  sqlserver_data:
